### ISSUE TITLE
Fix definition of 'simulation of population'

### ISSUE THREAD

**Issue by dillerm** [ApolloDev/apollo-sv#103]
Current definition is:

> A simulation of the aggregate of organisms that are members of the population participating in a simulator.

Will want to change it so that it doesn't specify that some population is participating in a simulator. 

Will also want to capture that the simulation can take one or more input parameters and spits out one or more output parameters.

**Comment by dillerm** [comment]
Proposed change:

> A simulation of a population or populations of organisms of a particular biological taxon that estimates changes to a pre-specified set of population parameters over time.

**Comment by dillerm** [comment]
Just saw your comment on Issue #95 about population simulators being out of favor. I'm assuming, therefore, that this change is going to be very low priority, if we decide to make any changes at all.

**Comment by hoganwr** [comment]
No I think we should fix what's broken.  Simulators fundamentally are simulating processes, so I would refine your proposal to:

A simulation of a population or populations of organisms of a particular biological taxon that simulates a particular type of event or types of event that occur in a specified time interval.

**Comment by dillerm** [comment]
I like it. I'll go ahead and make the change the next time I'm editing the OWL file.
