### ISSUE TITLE
Review 'geographic location' class, and perhaps consider deleting it to create our own.

### ISSUE THREAD

**Issue by dillerm** [ApolloDev/apollo-sv#13]
Definition seems to be a bit circular, but because we're importing from GAZ we'll have to deprecate the class if we're going to make changes. At the very least, we should consider moving it since its definition elsewhere, as opposed to being a subclass of 'site'.

**Comment by dillerm** [comment]
We'll also want to review 'geographical region' since its name suggests that it belongs as a subclass of 'site'. I didn't open a separate issue for this because I figure both should be addressed simultaneously.

**Comment by hoganwr** [comment]
geographic location from GAZ is MIREOT'd by IAO.  so long as we're
importing all of IAO, we cannot remove it from Apollo-SV.

**Comment by hoganwr** [comment]
this is the same as issue #3
