### ISSUE TITLE
Add case series to Apollo-SV

### ISSUE THREAD

**Issue by hoganwr** [ApolloDev/apollo-sv#162]
parent is most likely dataset

We have "infection case list" but that corresponds to a different XSD type.   There is an XSD type called CaseSeries for which we do not have a class at the moment, apparently.

We'll need to differentiate CaseList from CaseSeries.

**Comment by dillerm** [comment]
Here is the definition we arrived at: "An investigation that has, as part, a population survey with an objective to count all participants in some disease outcome or some exposure process."
