### ISSUE TITLE
Definition of CaseSeries requires revision

### ISSUE THREAD

**Issue by JohnLevander** [ApolloDev/apollo-sv#179]
From Mike: "The Apollo SV definition of Case Series is wrong. A case series doesn't necessarily represent the results of an effort to count cases. It may involve some effort to identify all cases, but by no means is that definitional and it probably isn't even an aspect of the majority of case series."

**Comment by hoganwr** [comment]
In particular, this paper that examines the definitions of and distinctions between case series and cohort studies, says that completeness is not necessary in a case series:
https://www.ncbi.nlm.nih.gov/pubmed/22213493

**Comment by dillerm** [comment]
Not sure how restrictive we want to be with our definitions, but could we amend the definition to say that the objective is "...to count _some collection of organisms that are participant_ in some disease outcome or some exposure process," (italics indicate amendment)?

**Comment by dillerm** [comment]
After some review, I've decided to go ahead and propose the following definition for 'case series':

> An investigation that concretizes some [disease state design](http://www.ontobee.org/ontology/OBI?iri=http://purl.obolibrary.org/obo/OBI_0001293) and that has as an occurrent part some [population survey](http://www.ontobee.org/ontology/APOLLO_SV?iri=http://purl.obolibrary.org/obo/APOLLO_SV_00000152) that has specified input some [case definition](http://www.ontobee.org/ontology/APOLLO_SV?iri=http://purl.obolibrary.org/obo/APOLLO_SV_00000296).

**Comment by hoganwr** [comment]
Should be:

An investigation that *realizes* some disease state design
<http://www.ontobee.org/ontology/OBI?iri=http://purl.obolibrary.org/obo/OBI_0001293>
and
that has as an occurrent part some population survey
<http://www.ontobee.org/ontology/APOLLO_SV?iri=http://purl.obolibrary.org/obo/APOLLO_SV_00000152>
that
has specified input some case definition
<http://www.ontobee.org/ontology/APOLLO_SV?iri=http://purl.obolibrary.org/obo/APOLLO_SV_00000296>
.

**Comment by dillerm** [comment]
My apologies for dropping the ball on getting this added. If you see no need for any further discussion, I can go ahead and fix the definition accordingly.
