### ISSUE TITLE
Need identifiers for new control measures

### ISSUE THREAD

**Issue by JohnLevander** [ApolloDev/apollo-sv#190]
In the MDC we have software that the supports the following control measures, but I can't find these control measures in Apollo-SV:

1. antibiotic prophylaxis
2. antiviral prophylaxis of the symptomatic
3. antiviral treatment of the symptomatic
4. global school closures
5. hospitalization with administration of intravenous antibiotics
6. mass drug deployment
7. reactive school closures
8. treatment in the i.c.u.

Can we add them?  Or if they are already there, can you please point me to what you think I should use for each control measure?

FYI, as an example, here is how we use XML to state that software supports the vaccination control measure as defined by Apollo-SV:

    <controlMeasures>
        <identifier>
            <identifier>APOLLO_SV_00000136</identifier>
            <identifierSource>https://biosharing.org/bsg-s002688</identifierSource>
            <identifierDescription>vaccination</identifierDescription>
        </identifier>
    </controlMeasures>

**Comment by dillerm** [comment]
Hey @JohnLevander, it looks as if we've addressed the above issue, so I'm going to go ahead and close it. Feel free to re-open it if you do end up needing us to create additional control measures.
