### ISSUE TITLE
EPIC ODK Migration of Apollo SV

### ISSUE THREAD

**Issue by matentzn** [ApolloDev/apollo-sv#225]
This ticket is about the migration of Apollo SV to ODK, including documentation, quality control and more. I will take care of this ticket, but the dependencies below should be dealt with by the Apollo SV team:

# Dependencies

- [x] #217 
- [x] #219 
- [x] #218 
- [x] #221
- [x] #222
- [x] #223
- [x] #224
- [x] #226

**Comment by dillerm** [comment]
@matentzn do you mind if I get started on these?

**Comment by matentzn** [comment]
You dont need to - I know what to do (already met with @dillerm)

But I would be very happy to work on this stuff with you together? Would you like to meet and we close all these issues in a meeting together?

**Comment by dillerm** [comment]
Sure, I'm free all day today and much of next week.

**Comment by matentzn** [comment]
Sorry, I am travelling (in Venice atm). I sent you an invite to my earliest possible timeslot. Can you make that?

**Comment by dillerm** [comment]
Yes, that works for me. Enjoy your travels!

**Comment by matentzn** [comment]
Thanks :)
