### ISSUE TITLE
Apollo SV axioms outside OWL 2 DL

### ISSUE THREAD

**Issue by matentzn** [ApolloDev/apollo-sv#226]
Three logical definitions are firmly outside of OWL 2 DL, which I strongly recommend to drop without replacement:

- APOLLO_SV_00000338
- APOLLO_SV_00000356
- APOLLO_SV_00000596

I do not know exactly, exactly what the problem with this is, but it seems you cannot combine "has participant" with "min 2" type restrictions.

OWL 2 DL Profile Report: Ontology and imports closure NOT in profile. The following violations are present:
Use of non-simple property in a restriction: ObjectMinCardinality(2 <http://purl.obolibrary.org/obo/RO_0000057> <http://purl.obolibrary.org/obo/OBI_0100026>) [EquivalentClasses(<http://purl.obolibrary.org/obo/APOLLO_SV_00000338> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/APOLLO_SV_00000596> ObjectIntersectionOf(ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000117> <http://purl.obolibrary.org/obo/APOLLO_SV_00000371>) ObjectMinCardinality(2 <http://purl.obolibrary.org/obo/RO_0000057> <http://purl.obolibrary.org/obo/OBI_0100026>)))) in OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/apollo_sv.owl>) VersionIRI(<http://purl.obolibrary.org/obo/apollo_sv/releases/2023-02-19/apollo_sv.owl>))]
Use of non-simple property in a restriction: ObjectMinCardinality(2 <http://purl.obolibrary.org/obo/RO_0000057> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/OBI_0100026> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002325> <http://purl.obolibrary.org/obo/OBI_0100026>))) [EquivalentClasses(<http://purl.obolibrary.org/obo/APOLLO_SV_00000356> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/APOLLO_SV_00000340> ObjectMinCardinality(2 <http://purl.obolibrary.org/obo/RO_0000057> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/OBI_0100026> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002325> <http://purl.obolibrary.org/obo/OBI_0100026>))))) in OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/apollo_sv.owl>) VersionIRI(<http://purl.obolibrary.org/obo/apollo_sv/releases/2023-02-19/apollo_sv.owl>))]
Use of non-simple property in a restriction: ObjectMinCardinality(2 <http://purl.obolibrary.org/obo/RO_0000057> <http://purl.obolibrary.org/obo/OBI_0100026>) [EquivalentClasses(<http://purl.obolibrary.org/obo/APOLLO_SV_00000596> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/GO_0044419> ObjectIntersectionOf(ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000117> <http://purl.obolibrary.org/obo/GO_0051705>) ObjectMinCardinality(2 <http://purl.obolibrary.org/obo/RO_0000057> <http://purl.obolibrary.org/obo/OBI_0100026>)))) in OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/apollo_sv.owl>) VersionIRI(<http://purl.obolibrary.org/obo/apollo_sv/releases/2023-02-19/apollo_sv.owl>))]

**Comment by hoganwr** [comment]
has participant is a non-simple relation by virtue of being in a property chain with the non-simple relation has part.

You cannot use qualified cardinality restrictions with non-simple relations.  That alone would make the logic undecidable.

**Comment by matentzn** [comment]
@hoganwr agrees to remove all of these but make sure classification does not break.
