### ISSUE TITLE
Change label of 'geographical migration of organism' 

### ISSUE THREAD

**Issue by dillerm** [ApolloDev/apollo-sv#235]
The use of 'migration' in this label is confusing since this term tends to imply permanent or semipermanent settling at the destination. I think changing it to "geographical displacement of organism" or "organism travel" and adding a comment that clarifies that the organism need not permanently/semi-permanently settle at their destination avoids this issue.

**Comment by hoganwr** [comment]
'displacement' has a negative connotation, like the organism was forced to
move against its own preferences / dispositions.  On the other hand,
'travel' implies too much intentionality if we're going for non-human as
well as human.  I do not have a better suggestion at the moment, but will
continue to consider.

**Comment by dillerm** [comment]
I think we're overthinking this and that "geographical movement of organism" is sufficient so long as we're careful to say that there is an origin that the organism leaves from and a destination to which it ends up. This destination may end up being identical to the origin and it need not be intentionally traveled to (or at least have been a goal to travel to prior to or at the start of traveling). Thus, it's neutral with respect to intentionality, but specific enough so that simply walking around your yard or home doesn't count.

**Comment by hoganwr** [comment]
I like “geographical movement of organism”
