### ISSUE TITLE
Superclass for 'infection' ('reproduction') is now obsolete

### ISSUE THREAD

**Issue by emmachappell** [ApolloDev/apollo-sv#246]
It looks like the term 'reproduction' has been removed from the Gene Ontology, but this hasn't been reflected in Apollo's ontology or the definition for the term 'infection.' Seems worth it to update.

**Comment by hoganwr** [comment]
Thanks! Sadly GO is not imported into Apollo-SV is a nice ODK way. So this
raises the larger issue of properly ODK-ifying the GO import. Which we'll
do, but it means a fair amount of work, and thus this won't happen
immediately. But I'm on it.

**Comment by dillerm** [comment]
Make sure we replace this with 'reproductive process' (GO:0022414). See: https://amigo.geneontology.org/amigo/term/GO:0000003.

**Comment by hoganwr** [comment]
NO. See my notes.

**Comment by hoganwr** [comment]
Specifically my notes in the PR #247
