### ISSUE TITLE
Revisit definition for 'simulation'

### ISSUE THREAD

**Issue by dillerm** [ApolloDev/apollo-sv#26]
Current definition is: "A purely intentional entity that simulates an entity and its properties."

This definition is circular since 'simulate' is not defined in Apollo. Furthermore, it would be more accurate to say that it is the instantiation of some model over a specified time interval.

We should then create a class for 'model' that might be defined as, "A purely intentional entity that concretizes some class of particulars and is a theoretical composite of the qualities and dispositions that are unique to that class, but whose instance is brought about by the output of some material processing or algorithm and is subject to input from a finite number of specified information content entities."

**Comment by hoganwr** [comment]
This is patently untrue.  There is a simulates object property, which references the process of simulating.  Both the object property and the class 'simulating of process of type X' have definitions.

**Comment by dillerm** [comment]
Sorry about that. I could have sworn I double-checked for this, too. Guess I must have missed it.
