### ISSUE TITLE
Consider removing MIREOT'd term 'symbiosis' and creating our own class

### ISSUE THREAD

**Issue by dillerm** [ApolloDev/apollo-sv#30]
The current definition for the term only incorporates mutualism, commensalism, and parasitism, while we're including all interspecies interactions under the term. Therefore, we should either remove the MIREOT of this term and create our own definition, or move certain terms, such as 'antagonism', so that they're subclasses of 'interspecies interaction between organisms'. Personally, I think we should go with the former of the two options since it requires the least amount of work without sacrificing any consistency with a large portion of the literature and without sacrificing the logical relations between classes. Moreover, I think that this option is preferable to the latter because it allows 'predation' and 'grazing' to be subclasses of 'symbiosis' (although not directly), which quite frankly seems like a rather obvious place for them.

**Comment by dillerm** [comment]
To follow up, here is the link to GO's definition of 'symbiosis': http://www.ontobee.org/ontology/GO?iri=http://purl.obolibrary.org/obo/GO_0044403.

There are a few caveats, I think, with how they define the term, all of which I will outline below:

1. As stated previously, their definition implies that symbiosis only encompasses mutualism, parasitism, and commensalism (i.e., they're explicitly using the de Bary definition). Unfortunately, this definition ignores predation and grazing, both of which share only subtle dissimilarities with parasitoidism and parasitism, respectively, such that I believe the former two might in fact be subclasses of the latter two. Perhaps a counterargument to this would be that predation and grazing are interactions that lack in intimacy and that the organisms may not live together, although the dubiousness of such a claim is underscored by the fact that neither parameter is defined.

2. Their definition states that mutualistic, commensalistic, and parasitic interactions are often not discrete categories of interactions, but should rather be perceived as being a continuum of a single interaction. I disagree, on the grounds that there are distinct ontological differences between the interactions of, for example, commensal phenotypes and pathogenic phenotypes of certain species of bacteria that are of great interest to microbiologists who are trying to study these phenotypes.

3. Their definition precludes other interactions (e.g., amensalism, in which one organism is harmed while the other is unaffected) from being classified as symbiotic, despite there being no logical reason for why they aren't symbioses. For example, sheep trampling grass is an interaction between two organisms that live together in a fairly intimate association, yet while the sheep remain unaffected the grass is killed. This relationship can perhaps acquire a new dimension if the grass is the primary source of food for the sheep, in which case the interaction becomes antagonistic.

**Comment by hoganwr** [comment]
Matt, could you propose a new definition of 'symbiosis' that addresses these issues?

**Comment by dillerm** [comment]
Symbiosis = def. "An interspecies interaction between organisms living in some ecosystem in which at least one organism is harmed or benefits."

I was originally going to propose a second, alternative definition that would restrict symbiotic interactions to only those in which the actions of one organism has a direct causal influence on another. Still not sure whether this is an important distinction to make at this level of the hierarchy, though, as it can probably be handled elsewhere in various subclasses (e.g., competition).

**Comment by dillerm** [comment]
If this definition ends up being the one we go with, would this imply that 'interspecies integration between organisms' should be deprecated and replaced with 'symbiosis'? The alternative would be to add a stipulation that 'symbiosis' only encompasses interactions that have a _direct_ influence on another organism, while having a separate class for _indirect_ interactions. 

Another possible distinction that might be made is that symbiotic relationships don't seem to occur at the population level, with the exception of interspecies competition and one point of reference for pathogen-host interactions, wherein at least one population of organisms is having an effect on one or more organisms of another species. I have my doubts about this one, though, since our definitions seem to be able to switch from the individual level to the population level easily.
