### ISSUE TITLE
APOLLO_SV count vs STATO count?

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [ApolloDev/apollo-sv#50]
Hi folks, I was perusing your ontology and attracted to a number of APOLLO_SV terms - population census etc - that I'd import into GenEpiO.  One question though, I saw that you had a "count" term very similar to STATO's, and was wondering if this term was deliberate or an opportunity (MIEROT) for reuse.

Which raises another question - are there plans to make APOLLO_SV part of OBOFoundry / OntoFox  (I just checked and couldn't see it there)?
Regards,

Damion

**Comment by dillerm** [comment]
Hi Damion, I believe the main difference between our class and theirs is that, by asserting that a 'count' is the specified output of '[counting](http://www.ontobee.org/ontology/APOLLO_SV?iri=http://purl.obolibrary.org/obo/APOLLO_SV_00000033)'

**Comment by dillerm** [comment]
Hi Damion, I believe the main difference between our class and STATO's is that we assert that a 'count' is the specified output of '[counting](http://www.ontobee.org/ontology/APOLLO_SV?iri=http://purl.obolibrary.org/obo/APOLLO_SV_00000033)'. In doing so, we specify that the count is about a finite set of entities (this is subsumed from the definition of 'counting'), rather than it being an exhaustive count of every individual of a particular class.

**Comment by Public-Health-Bioinformatics** [comment]
Good to tackle that fundamental definition of counting. I spotted the "count of simulated population" comment that result could be fractional.  Makes me also think of other things reported as counts, e.g. cups of flour left in this bag, or cups of coffee consumed by Fred on Tuesday, which might be reported as fractional, e.g. 1.5 cups, but we'd call those counts too.  So do you want a separate definition for counting where the input to the process is known to be a set of whole things, and another definition where the units of measure in the counting process are of a scale that allows for rounding?  (There'd be no fuss if the subatomic weight of everything was known.)

FYI, in GenEpiO, I'm also trying to anticipate the need to describe census counts at points in time and averaged or simulated datums of various counts involved in epidemiological outbreaks.

**Comment by dillerm** [comment]
Hi Damion, I apologize for the late reply here. This is something that I'll have to take a look at in more detail. I believe that count data are generally considered to be non-negative integers, and therefore that counts of simulated populations also take the form of non-negative integers. 

The fractional "counts" that the comment is referring to, I'm assuming, would be the output of some calculation that takes as input the simulated population counts (e.g., the counts of both the simulated susceptible population and the simulated infected population). Therefore, these fractional "counts," I believe, are in fact a different type of measurement data. [Wikipedia describes this pretty well](https://en.wikipedia.org/wiki/Count_data), as does this [slide set](http://fmwww.bc.edu/ec-c/s2013/327/S5CountCategorical0511.slides.pdf) that I found online.

As for the examples that you mentioned, I believe they would be the outputs of some sort of measurement process other than counting, and therefore would also not be considered counts.

**Comment by Public-Health-Bioinformatics** [comment]
Ok, I get how certain things like 'degrees of freedom' are intrinsically indivisible, as are raw counts of countable entities. Thanks for the links, I'll have a look. Am pondering edge cases where model/simulator might benefit from having fractional numbers rather than rounding issues presented by counts over time. Sounds though like that forces stats to be separated out to a separate layer that works only on rounded numbers.  Oy!
