### ISSUE TITLE
Fix UAL on 'treatment preventable outcome' and discuss adding to definition.

### ISSUE THREAD

**Issue by dillerm** [ApolloDev/apollo-sv#68]
> treatment preventable outcome = (def) An objective specification that specifies the disease outcome that a treatment seeks to prevent.

UAL will need to be changed to 'TreatmentPreventableOutcomeEnum', or the class will need to be removed from the ontology altogether. Previously we discussed not adding any classes for enumerated types to Apollo-SV. 

Currently the enumeration values are as follows:
- infection
- infectiousness
- sickness requiring medical attention
- sickness requiring intensive care
- death

My proposal is to change the definition to better reflect this list of options, particularly 'sickness requiring medical attention' and 'sickness requiring intensive care', and strap 'Enum' onto the end of the UAL, which currently is just 'TreatmentPreventableOutcome'. Note that there is no class with that title.

**Comment by hoganwr** [comment]
Don't see any point in wasting effort on UALs at this point.  We should be spending our efforts instead on what the group decided would be the new way to link SV and the XSD

**Comment by dillerm** [comment]
I imagine that I'll want to go ahead and fix this since we'll still be using the UALs.
