### ISSUE TITLE
Create new class "disease transmission tree estimator"

### ISSUE THREAD

**Issue by hoganwr** [ApolloDev/apollo-sv#92]
Create a new class with rdfs:label "disease transmission tree estimator"
Editor preferred term: "algorithm for estimating disease transmission as a tree data structure"
Parent class: algorithm
Approximate definition that likely requires refinement (ADLRR, pronounced "adler"): "an algorithm that constructs a tree data structure that represents a collection of infection-acquisition-from-infectious-host events in a given population or subpopulation during a specific time frame."
rdfs:comment: "these algorithms often use genetic sequence data as input to help estimate the transmission tree"

**Comment by dillerm** [comment]
We have a class called 'transmission tree', although it's defined as being about some epidemic, whereas the tree constructed by an estimator might not necessarily have some aboutness to an epidemic. Perhaps we should change the definition of 'transmission tree' to include that it can be about the concretization of an 'epidemic model'? 

> transmission tree - A data structure that represents, for a particular epidemic, a subset of infected organisms and for each infected organism in the subset, except the first one infected temporally, its infection acquisition from an infected host as a machine-readable link to that infected host.

**Comment by hoganwr** [comment]
We could change the definition of transmission tree to use "infection in ecosystem" in place of "epidemic" so we're not constrained to epidemics.

**Comment by dillerm** [comment]
Agreed.

**Comment by dillerm** [comment]
I'm assuming that the definition for this class should now be, "An algorithm that constructs a transmission tree," right?

**Comment by hoganwr** [comment]
I would say "has specified output" at least one transmission tree.

**Comment by dillerm** [comment]
Got it. Will add to Apollo-SV today.
