### ISSUE TITLE
Create new class "population dynamics model"

### ISSUE THREAD

**Issue by hoganwr** [ApolloDev/apollo-sv#93]
rdfs:label: "population dynamics model"
editor preferred term: "model of population dynamics"
ADLRR: "an algorithm that simulates changes in the size and life stage distribution of a population or populations of organisms of a particular biological taxon."

**Comment by dillerm** [comment]
We have a class called 'simulation of population', which is defined as:

> A simulation of the aggregate of organisms that are members of the population participating in a simulator.

I like your definition better, though if the two aren't synonymous, then we should consider making this a subclass of 'simulation of population'.

**Comment by hoganwr** [comment]
The definition is a bit weird - not sure what it means for a population to participate in a simulator.  Plus this is more specifically about certain events in the population as opposed to leaving it open to any/all events.

**Comment by dillerm** [comment]
Got it. I'm going to log an issue for changing that definition of 'simulation of population'. As for this definition, I don't see any other need for discussion of it, unless you have anything else to add.

**Comment by hoganwr** [comment]
Nope.  Nothing to add.
