### ISSUE TITLE
Add definition to existing class 'agent-level ecosystem generator'

### ISSUE THREAD

**Issue by hoganwr** [ApolloDev/apollo-sv#94]
rdfs:label "synthetic ecosystem constructor"
alternative_term: "synthetic ecosystem generator"
editor preferred term: "synthetic ecosystem constructor"
parent class: software
ADLRR: "software that has one or more synthetic ecosystem datasets as output"

**Comment by dillerm** [comment]
We currently have a class called 'agent-level ecosystem data generator' in Apollo-SV, but it doesn't have a definition. 

Another class that may be of interest here is 'agent-level ecosystem census', which is defined as:

> A data set that is the specified output of a agent-level ecosystem data generation that had census data as an input.

Given that synthetic population ecosystem datasets represent population features at the agent-level, I would say that the two are synonymous. 

Therefore, 'synthetic ecosystem constructor' would be:

"Software whose concretization is realized as an agent-level ecosystem data generation."

We can then define 'agent-level ecosystem data generation' as:

"A planned process that takes two or more census data sets as input, and that has one or more synthetic ecosystem data sets as output."

**Comment by hoganwr** [comment]
Matt, good catch!  Use the existing class, then.

**Comment by dillerm** [comment]
Should I add 'synthetic ecosystem constructor' as an editor-preferred term?
