### ISSUE TITLE
Create new class "disease surveillance data"

### ISSUE THREAD

**Issue by hoganwr** [ApolloDev/apollo-sv#96]
rdfs:label "disease surveillance data"
editor preferred term: "disease surveillance data set"
parent: data set
ADLRR: "a data set that is the output of a planned process that is the realization of a disease surveillance objective specification."

We probably then also need a class "disease surveillance objective specification", parent: objective specification, editor preferred term: "disease surveillance objective specification", ADLRR: "an objective specification whose endpoint is human awareness of the level of a particular disease in a particular population of a given biological taxon during some time interval."

**Comment by dillerm** [comment]
Would this be distinct from 'count of disease cases' since the data set would include counts of disease cases, in addition to data on demographics or health status, for example?

**Comment by hoganwr** [comment]
Yes, it's distinct.  Surveillance data often includes more than just counts of cases, although including counts of disease cases is necessary.

**Comment by dillerm** [comment]
I think, then, that we should create a class for disease surveillance. We already need one anyway for indexing some of the MIDAS papers. I'll work on a definition.

**Comment by dillerm** [comment]
I'm going to go ahead and add this to Apollo, except I'm going to define it as "A data set that is about some disease surveillance," the latter of which was recently created and defined in Apollo as "A planned process that is the realization of a disease surveillance objective specification."
