### ISSUE TITLE
Create new class "mortality data"

### ISSUE THREAD

**Issue by hoganwr** [ApolloDev/apollo-sv#97]

**Comment by hoganwr** [comment]
rdfs:label "mortality data"
editor preferred term "population mortality data set"
parent: data set
ADLRR: "a data set that is about either the number of death events or the death events themselves of some individuals of a given population of a particular biological taxon over a given time interval."

**Comment by dillerm** [comment]
I'm wondering, since we have 'mortality rate' in Apollo (see below for definition), if the definition could be condensed to: "A data set that is about either some mortality rate or the death events themselves of some individuals of a given population of a particular biological taxon."

> mortality rate - A rate measurement datum that specifies the percentage of organisms within a population that have died over a given time interval.

**Comment by hoganwr** [comment]
Yes that definition seems fine.
